### PR TITLE
PINKTEAM-13-mongo-db-gcp-instance

### PR DESCRIPTION
**Pull request by Kova1DM**
* **Check if PR meets these requirements**
- [x] The commit message follows our guidelines
- [ ] Added tests for changes (for bug fixes/features)
- [ ] Documents added / updated (for bug fixes / features)

* **What change does this PR introduce?**
Install mongo database on gcp-instance with awx:
For test this you need install awx and add credentials to connect your gcp instance with awx, then run playbook

### CODE REVIEW

**Review by MaksymukNatalia — COMMENTED** [review]
Why are you checking the Ubuntu version?

**Comment by MaksymukNatalia** [comment]
> Why are you checking the Ubuntu version?

Discussed. Everything is cool but add template and description

**Review by MaksymukNatalia — APPROVED** [review]

**Comment by Kova1DM** [comment]
Sure, I will add

**Review by MaksymukNatalia — APPROVED** [review]

**Review by IaKoval — APPROVED** [review]
Accept

**Pull request merged**
